@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NzI4NjE0NjN9.e6xiCB6I23fkj8VOmUDD78olr2FrLJQpCueXonGGU6E

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Sam",
  "email": "s@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "s@test.com",
  "password": "password"
}

### Movies create
POST http://localhost:3000/movies.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "title": "test title",
  "image_url": "test image",
  "description": "test description"
}