@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE2NzM1MDQxODV9.yNvPLw30zDvr397xfmkspS3PYW4rFcTvokj94vaYoyg

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Ben",
  "email": "b@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "b@test.com",
  "password": "password"
}

### Movies create
# POST http://localhost:3000/movies.json
# Content-Type: application/json
# Authorization: Bearer {{jwt}}

# {
#   "title": "movie 7",
#   "year": "test 6",
#   "imdbID": "test 6",
#   "poster": "test 6"
# }

### Movies index
GET http://localhost:3000/movies.json

### Movies show
GET http://localhost:3000/movies/1.json

### Movies update
PATCH http://localhost:3000/movies/8
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "test2"
}

### Movies destory
DELETE http://localhost:3000/movies/8
Authorization: Bearer {{jwt}}

### Favorites create
POST http://localhost:3000/favorites.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "user_id": 7,
  "id": 2
}

### Favorites index
GET http://localhost:3000/favorites

### Favorites show
GET http://localhost:3000/favorites/3.json

# ### Favorites update
# PATCH http://localhost:3000/favorites/3
# Authorization: Bearer {{jwt}}
# Content-Type: application/json

# {
#   "image_url": "testtesttest"
# }

### Favorites destory
DELETE http://localhost:3000/favorites/3
Authorization: Bearer {{jwt}}

### 
# curl --request GET \
#   --url 'https://api.themoviedb.org/4/movie?api_key=8856f48be68d7285c433496838dbffb4' \
#   --header 'Content-Type: application/json;charset=utf-8'