### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Christine",
  "email": "christine@test.com",
  "password": "password",
  "password_confirmation": "password"
}